defmodule Day11Test do
  use ExUnit.Case

  test "test part 1 example" do
    input = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

    want = 374
    got = Day11.Part1.solver(input)

    assert want == got
  end

  test "expand galaxy map" do
    input = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

    want = """
    ....#........
    .........#...
    #............
    .............
    .............
    ........#....
    .#...........
    ............#
    .............
    .............
    .........#...
    #....#.......
    """

    got =
      input
      |> String.split("\n", trim: true)
      |> Enum.map(&String.to_charlist(&1))
      |> Nx.tensor(names: [:rows, :cols])
      |> Day11.Part1.get_expanded_galaxy()

    assert got |> String.trim_trailing() == want |> String.trim_trailing()
  end

end
